[versions]
luaj = "3.0.1"
gson = "2.10.1"
logback = "1.4.14"

[libraries]
luaj-jse = { module = "org.luaj:luaj-jse", version.ref = "luaj" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.1.20" }
